;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-colon
        c-electric-pound
        ))

(setq mc/cmds-to-run-once
      '(
        c-electric-delete-forward
        c-electric-paren
        c-electric-star
        hs-toggle-hiding
        suspend-frame
        ))
